kind: Service
apiVersion: v1
metadata:
  name: demo
  labels:
    name: demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:           
    app: demo        

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
      matchLabels:
        app: demo
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: linjudock19/demo
          ports:
            - containerPort: 8080